###########################################################################
## Makefile generated for MATLAB file/project 'create2dEpi_codegen'. 
## 
## Makefile     : create2dEpi_codegen_rtw.mk
## Generated on : Thu Oct 17 16:36:09 2019
## MATLAB Coder version: 4.3 (R2019b)
## 
## Build Info:
## 
## Final product: ./create2dEpi_codegen.a
## Product type : static-library
## 
###########################################################################

###########################################################################
## MACROS
###########################################################################

# Macro Descriptions:
# PRODUCT_NAME            Name of the system to build
# MAKEFILE                Name of this makefile
# MODELLIB                Static library target

PRODUCT_NAME              = create2dEpi_codegen
# MAKEFILE                  = create2dEpi_codegen_rtw.mk
# MATLAB_ROOT               = /opt/apps/MATLAB/R2019b
# MATLAB_BIN                = /opt/apps/MATLAB/R2019b/bin
MAKEFILE                  = makefile
MATLAB_ROOT               = /usr/local/MATLAB/R2017a
MATLAB_BIN                = /usr/local/MATLAB/R2017a/bin
MATLAB_ARCH_BIN           = $(MATLAB_BIN)/glnxa64
MASTER_ANCHOR_DIR         = 
# START_DIR                 = $(HOME)/repositories/kamTools/matlab/mex/codegen/lib/create2dEpi_codegen
START_DIR                 = $(HOME)/repositories/fidall-bruker/fidall/lib/src/lib
TGT_FCN_LIB               = ISO_C
SOLVER_OBJ                = 
CLASSIC_INTERFACE         = 0
MODEL_HAS_DYNAMICALLY_LOADED_SFCNS = 
RELATIVE_PATH_TO_ANCHOR   = .
C_STANDARD_OPTS           = -m32 -fwrapv -std=c99 -pedantic
CPP_STANDARD_OPTS         = -m32 -fwrapv -std=c++98 -pedantic -Wno-long-long
MODELLIB                  = create2dEpi_codegen.a

###########################################################################
## TOOLCHAIN SPECIFICATIONS
###########################################################################

# Toolchain Name:          GNU gcc/g++ | gmake (64-bit Linux)
# Supported Version(s):    
# ToolchainInfo Version:   2019b
# Specification Revision:  1.0
# 
#-------------------------------------------
# Macros assumed to be defined elsewhere
#-------------------------------------------

# C_STANDARD_OPTS
# CPP_STANDARD_OPTS

#-----------
# MACROS
#-----------

WARN_FLAGS         = -Wall -W -Wwrite-strings -Winline -Wstrict-prototypes -Wnested-externs -Wpointer-arith -Wcast-align
WARN_FLAGS_MAX     = $(WARN_FLAGS) -Wcast-qual -Wshadow
CPP_WARN_FLAGS     = -Wall -W -Wwrite-strings -Winline -Wpointer-arith -Wcast-align
CPP_WARN_FLAGS_MAX = $(CPP_WARN_FLAGS) -Wcast-qual -Wshadow

TOOLCHAIN_SRCS = 
TOOLCHAIN_INCS = 
TOOLCHAIN_LIBS = 

#------------------------
# BUILD TOOL COMMANDS
#------------------------

# C Compiler: GNU C Compiler
CC = gcc

# Linker: GNU Linker
LD = g++

# C++ Compiler: GNU C++ Compiler
CPP = g++

# C++ Linker: GNU C++ Linker
CPP_LD = g++

# Archiver: GNU Archiver
AR = ar

# MEX Tool: MEX Tool
MEX_PATH = $(MATLAB_ARCH_BIN)
MEX = "$(MEX_PATH)/mex"

# Download: Download
DOWNLOAD =

# Execute: Execute
EXECUTE = $(PRODUCT)

# Builder: GMAKE Utility
MAKE_PATH = %MATLAB%/bin/glnxa64
MAKE = "$(MAKE_PATH)/gmake"


#-------------------------
# Directives/Utilities
#-------------------------

CDEBUG              = -g
C_OUTPUT_FLAG       = -o
LDDEBUG             = -g
OUTPUT_FLAG         = -o
CPPDEBUG            = -g
CPP_OUTPUT_FLAG     = -o
CPPLDDEBUG          = -g
OUTPUT_FLAG         = -o
ARDEBUG             =
STATICLIB_OUTPUT_FLAG =
MEX_DEBUG           = -g
RM                  = @rm -f
ECHO                = @echo
MV                  = @mv
RUN                 =

#----------------------------------------
# "Faster Builds" Build Configuration
#----------------------------------------

ARFLAGS              = ruvs
CFLAGS               = -m32 -c $(C_STANDARD_OPTS) -fPIC \
                       -O0
CPPFLAGS             = -m32 -c $(CPP_STANDARD_OPTS) -fPIC \
                       -O0
CPP_LDFLAGS          = -m32 -Wl,-rpath,"$(MATLAB_ARCH_BIN)",-L"$(MATLAB_ARCH_BIN)"
CPP_SHAREDLIB_LDFLAGS  = -m32 -shared -Wl,-rpath,"$(MATLAB_ARCH_BIN)",-L"$(MATLAB_ARCH_BIN)" -Wl,--no-undefined
DOWNLOAD_FLAGS       =
EXECUTE_FLAGS        =
LDFLAGS              = -m32 -Wl,-rpath,"$(MATLAB_ARCH_BIN)",-L"$(MATLAB_ARCH_BIN)"
MEX_CPPFLAGS         =
MEX_CPPLDFLAGS       =
MEX_CFLAGS           =
MEX_LDFLAGS          =
MAKE_FLAGS           = -f $(MAKEFILE)
SHAREDLIB_LDFLAGS    = -m32 -shared -Wl,-rpath,"$(MATLAB_ARCH_BIN)",-L"$(MATLAB_ARCH_BIN)" -Wl,--no-undefined



###########################################################################
## OUTPUT INFO
###########################################################################

PRODUCT = ../../libcreateEpi.a
PRODUCT_TYPE = "static-library"
BUILD_TYPE = "Static Library"

###########################################################################
## INCLUDE PATHS
###########################################################################

INCLUDES_BUILDINFO = -I$(START_DIR) -I$(MATLAB_ROOT)/extern/include -I$(MATLAB_ROOT)/simulink/include -I$(MATLAB_ROOT)/rtw/c/src -I$(MATLAB_ROOT)/rtw/c/src/ext_mode/common -I$(MATLAB_ROOT)/rtw/c/ert

INCLUDES = $(INCLUDES_BUILDINFO)

###########################################################################
## DEFINES
###########################################################################

DEFINES_CUSTOM = 
DEFINES_STANDARD = -DMODEL=create2dEpi_codegen -DHAVESTDIO -DUSE_RTMODEL -DUNIX

DEFINES = $(DEFINES_CUSTOM) $(DEFINES_STANDARD)

###########################################################################
## SOURCE FILES
###########################################################################

SRCS = $(START_DIR)/create2dEpi_output.c $(START_DIR)/main.c $(START_DIR)/create2dEpi_codegen_rtwutil.c $(START_DIR)/create2dEpi_codegen_data.c $(START_DIR)/create2dEpi_codegen_initialize.c $(START_DIR)/create2dEpi_codegen_terminate.c $(START_DIR)/create2dEpi_codegen.c $(START_DIR)/colon.c $(START_DIR)/print_processing.c $(START_DIR)/fileManager.c $(START_DIR)/repmat.c $(START_DIR)/diff.c $(START_DIR)/fliplr.c $(START_DIR)/trapz.c $(START_DIR)/cumtrapz.c $(START_DIR)/interp1.c $(START_DIR)/find.c $(START_DIR)/nullAssignment.c $(START_DIR)/unique.c $(START_DIR)/create2dEpi_codegen_emxutil.c $(START_DIR)/create2dEpi_codegen_emxAPI.c

ALL_SRCS = $(SRCS)

###########################################################################
## OBJECTS
###########################################################################

OBJS = create2dEpi_output.o main.o create2dEpi_codegen_rtwutil.o create2dEpi_codegen_data.o create2dEpi_codegen_initialize.o create2dEpi_codegen_terminate.o create2dEpi_codegen.o colon.o print_processing.o fileManager.o repmat.o diff.o fliplr.o trapz.o cumtrapz.o interp1.o find.o nullAssignment.o unique.o create2dEpi_codegen_emxutil.o create2dEpi_codegen_emxAPI.o

ALL_OBJS = $(OBJS)

###########################################################################
## PREBUILT OBJECT FILES
###########################################################################

PREBUILT_OBJS = 

###########################################################################
## LIBRARIES
###########################################################################

LIBS = 

###########################################################################
## SYSTEM LIBRARIES
###########################################################################

SYSTEM_LIBS =  -lm

###########################################################################
## ADDITIONAL TOOLCHAIN FLAGS
###########################################################################

#---------------
# C Compiler
#---------------

CFLAGS_BASIC = $(DEFINES) $(INCLUDES)

CFLAGS += $(CFLAGS_BASIC)

#-----------------
# C++ Compiler
#-----------------

CPPFLAGS_BASIC = $(DEFINES) $(INCLUDES)

CPPFLAGS += $(CPPFLAGS_BASIC)

###########################################################################
## INLINED COMMANDS
###########################################################################

###########################################################################
## PHONY TARGETS
###########################################################################

.PHONY : all build clean info prebuild download execute


all : build
	@echo "### Successfully generated all binary outputs."


build : prebuild $(PRODUCT)


prebuild : 


download : $(PRODUCT)


execute : download


###########################################################################
## FINAL TARGET
###########################################################################

#---------------------------------
# Create a static library         
#---------------------------------

$(PRODUCT) : $(OBJS) $(PREBUILT_OBJS)
	@echo "### Creating static library "$(PRODUCT)" ..."
	$(AR) $(ARFLAGS)  $(PRODUCT) $(OBJS)
	@echo "### Created: $(PRODUCT)"


###########################################################################
## INTERMEDIATE TARGETS
###########################################################################

#---------------------
# SOURCE-TO-OBJECT
#---------------------

%.o : %.c
	$(CC) $(CFLAGS) -o "$@" "$<"


%.o : %.cpp
	$(CPP) $(CPPFLAGS) -o "$@" "$<"


%.o : $(RELATIVE_PATH_TO_ANCHOR)/%.c
	$(CC) $(CFLAGS) -o "$@" "$<"


%.o : $(RELATIVE_PATH_TO_ANCHOR)/%.cpp
	$(CPP) $(CPPFLAGS) -o "$@" "$<"


%.o : $(START_DIR)/%.c
	$(CC) $(CFLAGS) -o "$@" "$<"


%.o : $(START_DIR)/%.cpp
	$(CPP) $(CPPFLAGS) -o "$@" "$<"


%.o : $(START_DIR)/%.c
	$(CC) $(CFLAGS) -o "$@" "$<"


%.o : $(START_DIR)/%.cpp
	$(CPP) $(CPPFLAGS) -o "$@" "$<"


%.o : $(MATLAB_ROOT)/rtw/c/src/%.c
	$(CC) $(CFLAGS) -o "$@" "$<"


%.o : $(MATLAB_ROOT)/rtw/c/src/%.cpp
	$(CPP) $(CPPFLAGS) -o "$@" "$<"


create2dEpi_output.o : $(START_DIR)/create2dEpi_output.c
	$(CC) $(CFLAGS) -o "$@" "$<"


main.o : $(START_DIR)/main.c
	$(CC) $(CFLAGS) -o "$@" "$<"


create2dEpi_codegen_rtwutil.o : $(START_DIR)/create2dEpi_codegen_rtwutil.c
	$(CC) $(CFLAGS) -o "$@" "$<"


create2dEpi_codegen_data.o : $(START_DIR)/create2dEpi_codegen_data.c
	$(CC) $(CFLAGS) -o "$@" "$<"


create2dEpi_codegen_initialize.o : $(START_DIR)/create2dEpi_codegen_initialize.c
	$(CC) $(CFLAGS) -o "$@" "$<"


create2dEpi_codegen_terminate.o : $(START_DIR)/create2dEpi_codegen_terminate.c
	$(CC) $(CFLAGS) -o "$@" "$<"


create2dEpi_codegen.o : $(START_DIR)/create2dEpi_codegen.c
	$(CC) $(CFLAGS) -o "$@" "$<"


colon.o : $(START_DIR)/colon.c
	$(CC) $(CFLAGS) -o "$@" "$<"


print_processing.o : $(START_DIR)/print_processing.c
	$(CC) $(CFLAGS) -o "$@" "$<"


fileManager.o : $(START_DIR)/fileManager.c
	$(CC) $(CFLAGS) -o "$@" "$<"


repmat.o : $(START_DIR)/repmat.c
	$(CC) $(CFLAGS) -o "$@" "$<"


diff.o : $(START_DIR)/diff.c
	$(CC) $(CFLAGS) -o "$@" "$<"


fliplr.o : $(START_DIR)/fliplr.c
	$(CC) $(CFLAGS) -o "$@" "$<"


trapz.o : $(START_DIR)/trapz.c
	$(CC) $(CFLAGS) -o "$@" "$<"


cumtrapz.o : $(START_DIR)/cumtrapz.c
	$(CC) $(CFLAGS) -o "$@" "$<"


interp1.o : $(START_DIR)/interp1.c
	$(CC) $(CFLAGS) -o "$@" "$<"


find.o : $(START_DIR)/find.c
	$(CC) $(CFLAGS) -o "$@" "$<"


nullAssignment.o : $(START_DIR)/nullAssignment.c
	$(CC) $(CFLAGS) -o "$@" "$<"


unique.o : $(START_DIR)/unique.c
	$(CC) $(CFLAGS) -o "$@" "$<"


create2dEpi_codegen_emxutil.o : $(START_DIR)/create2dEpi_codegen_emxutil.c
	$(CC) $(CFLAGS) -o "$@" "$<"


create2dEpi_codegen_emxAPI.o : $(START_DIR)/create2dEpi_codegen_emxAPI.c
	$(CC) $(CFLAGS) -o "$@" "$<"


###########################################################################
## DEPENDENCIES
###########################################################################

$(ALL_OBJS) : rtw_proj.tmw $(MAKEFILE)


###########################################################################
## MISCELLANEOUS TARGETS
###########################################################################

info : 
	@echo "### PRODUCT = $(PRODUCT)"
	@echo "### PRODUCT_TYPE = $(PRODUCT_TYPE)"
	@echo "### BUILD_TYPE = $(BUILD_TYPE)"
	@echo "### INCLUDES = $(INCLUDES)"
	@echo "### DEFINES = $(DEFINES)"
	@echo "### ALL_SRCS = $(ALL_SRCS)"
	@echo "### ALL_OBJS = $(ALL_OBJS)"
	@echo "### LIBS = $(LIBS)"
	@echo "### MODELREF_LIBS = $(MODELREF_LIBS)"
	@echo "### SYSTEM_LIBS = $(SYSTEM_LIBS)"
	@echo "### TOOLCHAIN_LIBS = $(TOOLCHAIN_LIBS)"
	@echo "### CFLAGS = $(CFLAGS)"
	@echo "### LDFLAGS = $(LDFLAGS)"
	@echo "### SHAREDLIB_LDFLAGS = $(SHAREDLIB_LDFLAGS)"
	@echo "### CPPFLAGS = $(CPPFLAGS)"
	@echo "### CPP_LDFLAGS = $(CPP_LDFLAGS)"
	@echo "### CPP_SHAREDLIB_LDFLAGS = $(CPP_SHAREDLIB_LDFLAGS)"
	@echo "### ARFLAGS = $(ARFLAGS)"
	@echo "### MEX_CFLAGS = $(MEX_CFLAGS)"
	@echo "### MEX_CPPFLAGS = $(MEX_CPPFLAGS)"
	@echo "### MEX_LDFLAGS = $(MEX_LDFLAGS)"
	@echo "### MEX_CPPLDFLAGS = $(MEX_CPPLDFLAGS)"
	@echo "### DOWNLOAD_FLAGS = $(DOWNLOAD_FLAGS)"
	@echo "### EXECUTE_FLAGS = $(EXECUTE_FLAGS)"
	@echo "### MAKE_FLAGS = $(MAKE_FLAGS)"


clean : 
	$(ECHO) "### Deleting all derived files..."
	$(RM) $(PRODUCT)
	$(RM) $(ALL_OBJS)
	$(ECHO) "### Deleted all derived files."


